package com.booleanull.currencyapp.domain

enum class CurrenciesEnum(val title: String) {
    GBP("GBP"),
    HKD("HKD"),
    IDR("IDR"),
    ILS("ILS"),
    DKK("DKK"),
    INR("INR"),
    CHF("CHF"),
    MXN("MXN"),
    CZK("CZK"),
    SGD("SGD"),
    THB("THB"),
    HRK("HRK"),
    EUR("EUR"),
    MYR("MYR"),
    NOK("NOK"),
    CNY("CNY"),
    BGN("BGN"),
    PHP("PHP"),
    PLN("PLN"),
    ZAR("ZAR"),
    CAD("CAD"),
    ISK("ISK"),
    BRL("BRL"),
    RON("RON"),
    NZD("NZD"),
    TRY("TRY"),
    JPY("JPY"),
    RUB("RUB"),
    KRW("KRW"),
    USD("USD"),
    AUD("AUD"),
    HUF("HUF"),
    SEK("SEK"),
}